services:
  - type: web
    name: thehustleplace
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: TMDB_API_KEY
        sync: false # Will be set manually in Render dashboard
      - key: REDIS_HOST
        value: redis
      - key: REDIS_PORT
        value: 6379
      - key: REDIS_PASSWORD
        sync: false # Will be set manually if using Redis
      - key: REDIS_DB
        value: 0

  - type: redis
    name: thehustleplace-redis
    plan: starter
    maxmemoryPolicy: allkeys-lru
